### PR TITLE
when LSN over specified limit, then flush the LSN

### PR DESCRIPTION
**Pull request by klausvahter**
This PR is related to [this issue](https://github.com/eventuate-foundation/eventuate-cdc/issues/147).
Also I extracted the connection creation in PostgresWalClient to a separate class, so that it would be better to test it. I decided to mock the entire thing, because simulating LSN difference in integration tests seemed potentially unreliable.

### CODE REVIEW

**Comment by cer** [comment]
Thanks for contributing this very valuable PR. I'm sorry that I neglected to respond until now.

However, I have a quick question: would a simpler solution be to call offsetProcessor.saveOffset() within [checkMonitoringChange()](https://github.com/eventuate-foundation/eventuate-cdc/blob/2669b2184473234890ba8f4cfe5c529d6eeb0234/eventuate-local-java-cdc-connector-postgres-wal/src/main/java/io/eventuate/local/postgres/wal/PostgresWalClient.java#L283)

**Comment by klausvahter** [comment]
Do you mean calling the saveOffset() with the latest received LSN on each monitoring change without doing the LSN diff check?

**Comment by cer** [comment]
> Do you mean calling the saveOffset() with the latest received LSN on each monitoring change without doing the LSN diff check?

Yes.

**Comment by klausvahter** [comment]
OK, this makes sense. I think I was trying to be a bit more safe about it, not knowing if this constant flushing might affect performance, but now that I think, if there's constant traffic, then this would be the case anyway. I will do a new PR, hopefully in the following days.

**Pull request closed without merging**
